"""RabbitMQ routing keys (mirror libs/events)."""

EMAIL_VERIFICATION_REQUESTED = "email.verification_requested"
EMAIL_VERIFIED = "email.verified"
PASSWORD_RESET_REQUESTED = "password.reset_requested"
DONATION_CREATED = "donation.created"
DONATION_REVIEWED = "donation.reviewed"
DONATION_SCHEDULED = "donation.scheduled"
DONATION_COMPLETED = "donation.completed"
REQUEST_CREATED = "request.created"
REQUEST_APPROVED = "request.approved"
REQUEST_SCHEDULED = "request.scheduled"
REQUEST_COMPLETED = "request.completed"
GROUP_APPROVED = "group.approved"
GROUP_JOIN_REQUESTED = "group.join_requested"
GROUP_MEMBER_APPROVED = "group.member_approved"
LISTING_CREATED = "listing.created"
MESSAGE_SENT = "message.sent"
