"""RabbitMQ routing keys (mirror libs/events)."""

EMAIL_VERIFICATION_REQUESTED = "email.verification_requested"
EMAIL_VERIFIED = "email.verified"
PASSWORD_RESET_REQUESTED = "password.reset_requested"
PASSWORD_RESET_COMPLETED = "password.reset_completed"
CAMPAIGN_CREATED = "campaign.created"
CAMPAIGN_CLOSED = "campaign.closed"
CAMPAIGN_DELIVERED = "campaign.delivered"
CONTRIBUTION_CREATED = "contribution.created"
CONTRIBUTION_REVIEWED = "contribution.reviewed"
CONTRIBUTION_COMPLETED = "contribution.completed"
GROUP_CREATED = "group.created"
GROUP_APPROVED = "group.approved"
GROUP_JOIN_REQUESTED = "group.join_requested"
GROUP_MEMBER_APPROVED = "group.member_approved"
POST_CREATED = "post.created"
MESSAGE_SENT = "message.sent"
