CAMPAIGN_CREATED = "campaign.created"
CAMPAIGN_CLOSED = "campaign.closed"
CAMPAIGN_DELIVERED = "campaign.delivered"
CONTRIBUTION_CREATED = "contribution.created"
CONTRIBUTION_REVIEWED = "contribution.reviewed"
CONTRIBUTION_RECEIVED = "contribution.received"
CONTRIBUTION_COMPLETED = "contribution.completed"
